<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
		<RuntimeIdentifiers>win-x64;linux-x64;osx-x64</RuntimeIdentifiers>
		<LangVersion>Latest</LangVersion>
		<IsPackable>false</IsPackable>
		<RootNamespace>Daany.Unit.Test.DataFrame</RootNamespace>
		<Platforms>AnyCPU;x64</Platforms>
		<Testproject>true</Testproject>
		<Configurations>Debug;Release</Configurations>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
		<PackageReference Include="OxyPlot.Core" Version="2.2.0" />
		<PackageReference Include="xunit" Version="2.9.3" />
		<PackageReference Include="xunit.runner.utility" Version="2.9.3" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		
		<ProjectReference Include="..\..\src\daany.df\Daany.DataFrame.csproj" />
		<ProjectReference Include="..\..\src\daany.ext\Daany.DataFrame.Ext.csproj" />
		<ProjectReference Include="..\..\src\daany.lina\Daany.LinA.csproj" />
		<ProjectReference Include="..\..\src\daany.stat\Daany.Stat.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="XPlot.Plotly">
	    <HintPath>..\..\src\daany.ext\Plotly.Bin\XPlot.Plotly.dll</HintPath>
	  </Reference>
	</ItemGroup>

	<ItemGroup>
		<None Update="testdata\AirPassengers.csv">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="testdata\airpassengers_stl_result.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="testdata\desc_test_ds.csv">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="testdata\sample_data_with_missing_values.txt">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="testdata\earth_quake.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="testdata\filter_dataFrameSample.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="testdata\group_result_testdata.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="testdata\group_rolling_testdata.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="testdata\group_sample_testdata.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="testdata\monthly_acc_deaths_usa_1973_78.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="testdata\simple_data_frame.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="testdata\sort_expected_asc.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="testdata\sort_expected_desc.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="testdata\sort_sample.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="testdata\sort_sample02.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="testdata\sort_sample02_asc_sorted.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="testdata\sort_sample02_desc_sorted.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="testdata\telemetry.csv">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="testdata\titanic_full_1310.csv">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="testdata\titanic_train.csv">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="testdata\wCorrelationResults.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<!-- For Windows -->
		<Exec Condition="'$(OS)' == 'Windows_NT'" Command="xcopy /y &quot;$(SolutionDir)src\daany_rust\rust_lib\win32-x64\daany_rust_lib.dll&quot; &quot;$(TargetDir)&quot;" ContinueOnError="true" />

		<!-- For Linux -->
		<Exec Condition="'$(OS)' != 'Windows_NT' And '$(RuntimeIdentifier)' == 'linux-x64'" Command="cp $(SolutionDir)src/daany_rust/rust_lib/linux32-x64/daany_rust_lib.so $(TargetDir)" ContinueOnError="true" />
	</Target>
	<!--<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="xcopy /y &quot;$(SolutionDir)src\daany_rust\rust_lib\[OS]\release\daany_rust_lib.dll(so)&quot; &quot;$(TargetDir)&quot;" ContinueOnError="true" />
	</Target>-->
</Project>
