name:  Daany Build & Test on Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
defaults:
  run:
    shell: bash
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Linux
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build 
      run: dotnet build --no-restore -c Linux_Release
    - name: Test 
      run: dotnet test --no-build --verbosity normal -c Linux_Release   
