name: Publish NuGet Packages

on:
  release:
    types: [published]  # Runs only when a new release is published
  workflow_dispatch:
    inputs:
      nuget_version:
        description: "NuGet Package Version"
        required: true
        default: "2.2.1"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'  # Adjust based on your project

    - name: Restore Dependencies
      run: dotnet restore

    - name: Restore NuGet Packages
      run: nuget restore daany.sln

    - name: Pack NuGet Packages
      run: |
        nuget.exe pack nuget_specs/Daany.DataFrame_v2.nuspec -Properties Configuration=Release;Version=${{ github.event.inputs.nuget_version }} -IncludeReferencedProjects -OutputDirectory nuget/
        nuget.exe pack nuget_specs/Daany.DataFrame.Ext_v2.nuspec -Properties Configuration=Release;Version=${{ github.event.inputs.nuget_version }} -IncludeReferencedProjects -OutputDirectory nuget/
        nuget.exe pack nuget_specs/Daany.Stat_v2.nuspec -Properties Configuration=Release;Version=${{ github.event.inputs.nuget_version }} -IncludeReferencedProjects -OutputDirectory nuget/
        nuget.exe pack nuget_specs/Daany.LinA_v2.nuspec -Properties Configuration=Release;Version=${{ github.event.inputs.nuget_version }} -IncludeReferencedProjects -OutputDirectory nuget/
